links = {
    "account-logged-in": [],
    "airplane-mode-symbolic": [],
    "applications-chat-panel": [],
    "applications-email-panel": [],
    "appointment-symbolic": [],
    "microphone-sensitivity-high": [
        "audio-input-microphone-high-panel",
        "audio-input-microphone-high",
        "audio-recorder-on",
        "mic-ready",
        "mic-volume-high",
        "xfce4-mixer-record",
        "audio-input-microphone-none-panel",
        "mic-on",
    ],
    "microphone-sensitivity-low": [
        "audio-input-microphone-low",
        "audio-input-microphone-low-zero-panel",
        "xfce4-mixer-no-record",
    ],
    "microphone-sensitivity-medium": [
        "audio-input-microphone-medium",
        "mic-volume-low",
        "mic-volume-medium",
    ],
    "microphone-sensitivity-muted": [
        "audio-input-microphone-muted",
        "audio-recorder-off",
        "discord-tray-deafened",
        "discord-tray-muted",
        "mic-volume-muted",
        "mic-off",
    ],
    "audio-recorder-paused": [],
    "audio-volume-high-panel": [
        "audio-volume-high",
        "audio-volume-high-symbolic",
        "xfce4-mixer-no-muted",
        "xfce4-mixer-volume-high",
        "xfce4-mixer-volume-very-high",
        "volume-level-high-panel",
        "volume-level-high",
    ],
    "audio-volume-low-panel": [
        "audio-volume-low",
        "audio-volume-low-symbolic",
        "audio-volume-low-zero-panel",
        "xfce4-mixer-volume-low",
        "xfce4-mixer-volume-ultra-low",
        "discord-tray-connected",
        "volume-level-low-panel",
        "volume-level-low",
    ],
    "audio-volume-medium-panel": [
        "audio-volume-medium",
        "audio-volume-medium-symbolic",
        "xfce4-mixer-volume-low-medium",
        "xfce4-mixer-volume-medium",
        "volume-level-medium-panel",
        "volume-level-medium",
    ],
    "audio-volume-muted-blocking-panel": [
        "audio-volume-muted-blocking",
        "audio-volume-muted-panel",
        "audio-volume-muted",
        "audio-volume-muted-blocked-panel",
        "discord-tray-speaking",
        "audio-output-none-panel",
        "audio-output-none",
        "audio-volume-off",
        "volume-level-muted-panel",
        "volume-level-muted",
        "volume-level-none-panel",
        "volume-level-none",
        "xfce4-mixer-muted",
        "xfce4-mixer-volume-muted",
    ],
    "audio-volume-muted-blocking-symbolic": [],
    "audio-volume-muted-symbolic": [],
    "battery-100": [
        "battery-full-charged",
        "battery-full-symbolic",
        "gpm-battery-100",
        "gpm-primary-100",
        "gpm-ups-100",
        "xfce4-battery-full",
        "xfce4-battery-plugin",
        "xfpm-battery-full",
        "xfpm-primary-100",
        "xfpm-ups-100",
        "battery-full-charged-symbolic",
        "gpm-ac-adapter",
        "gpm-battery-charged",
        "gpm-primary-charged",
        "gpm-ups-charged",
        "xfpm-primary-charged",
        "xfpm-ups-charged",
        "battery_full",
        "xfpm-battery-100",
        "ac-adapter",
        "battery-charged",
        "battery_charged",
        "battery_plugged",
        "xfpm-ac-adapter",
        "battery-full",
    ],
    "battery-90": [
        "gpm-primary-090",
        "gpm-battery-090",
        "xfpm-ups-090",
        "gpm-ups-090",
        "battery-090",
        "xfpm-battery-090",
        "xfpm-primary-090",
    ],
    "battery-80": [
        "battery-good-symbolic",
        "gpm-battery-080",
        "gpm-primary-080",
        "gpm-ups-080",
        "xfce4-battery-good",
        "xfpm-battery-good",
        "xfpm-primary-080",
        "xfpm-ups-080",
        "battery-080",
        "xfpm-battery-080",
        "battery-good",
    ],
    "battery-70": [
        "gpm-primary-070",
        "gpm-battery-070",
        "xfpm-ups-070",
        "gpm-ups-070",
        "battery-070",
        "xfpm-battery-070",
        "xfpm-primary-070",
    ],
    "battery-60": [
        "battery-medium-symbolic",
        "gpm-battery-060",
        "gpm-primary-060",
        "gpm-ups-060",
        "xfce4-battery-ok",
        "xfpm-battery-ok",
        "xfpm-primary-060",
        "xfpm-ups-060",
        "battery-060",
        "xfpm-battery-060",
        "battery-medium",
    ],
    "battery-50": [
        "gpm-primary-050",
        "gpm-battery-050",
        "xfpm-ups-050",
        "gpm-ups-050",
        "battery-050",
        "xfpm-battery-050",
        "xfpm-primary-050",
    ],
    "battery-40": [
        "battery-040",
        "battery-low-symbolic",
        "gpm-battery-040",
        "gpm-primary-040",
        "gpm-ups-040",
        "xfce4-battery-low",
        "xfpm-battery-low",
        "xfpm-primary-040",
        "xfpm-ups-040",
        "xfpm-battery-040",
        "battery-low",
    ],
    "battery-30": [
        "gpm-primary-030",
        "gpm-battery-030",
        "xfpm-ups-030",
        "gpm-ups-030",
        "battery-030",
        "xfpm-battery-030",
        "xfpm-primary-030",
    ],
    "battery-20": [
        "battery-caution-symbolic",
        "gpm-battery-020",
        "gpm-primary-020",
        "gpm-ups-020",
        "xfce4-battery-caution",
        "xfce4-battery-critical",
        "xfpm-battery-caution",
        "xfpm-battery-critical",
        "xfpm-primary-020",
        "xfpm-ups-020",
        "battery-020",
        "xfpm-battery-020",
        "battery-caution",
    ],
    "battery-10": [
        "gpm-primary-010",
        "gpm-battery-010",
        "xfpm-ups-010",
        "gpm-ups-010",
        "battery-010",
        "xfpm-battery-010",
        "xfpm-primary-010",
    ],
    "battery-0": [
        "battery-empty-symbolic",
        "gpm-battery-000",
        "gpm-primary-000",
        "gpm-ups-000",
        "xfpm-primary-000",
        "xfpm-ups-000",
        "battery-000",
        "gpm-battery-empty",
        "xfpm-battery-000",
        "xfpm-battery-empty",
        "battery-empty",
    ],
    "battery-100-charging": [
        "battery-ac-adapter-symbolic",
        "battery-full-charging-symbolic",
        "gpm-battery-100-charging",
        "gpm-primary-100-charging",
        "gpm-ups-100-charging",
        "xfpm-battery-full-charging",
        "xfpm-primary-100-charging",
        "xfpm-ups-100-charging",
        "battery-full-charging",
        "xfpm-battery-100-charging",
        "xfce4-battery-full-charging",
    ],
    "battery-90-charging": [
        "gpm-primary-090-charging",
        "gpm-battery-090-charging",
        "xfpm-ups-090-charging",
        "gpm-ups-090-charging",
        "battery-090-charging",
        "xfpm-battery-090-charging",
        "xfpm-primary-090-charging",
    ],
    "battery-80-charging": [
        "battery-good-charging-symbolic",
        "gpm-battery-080-charging",
        "gpm-primary-080-charging",
        "gpm-ups-080-charging",
        "xfce4-battery-good-charging",
        "xfpm-battery-good-charging",
        "xfpm-primary-080-charging",
        "xfpm-ups-080-charging",
        "battery-080-charging",
        "xfpm-battery-080-charging",
        "battery-good-charging",
    ],
    "battery-70-charging": [
        "gpm-primary-070-charging",
        "gpm-battery-070-charging",
        "xfpm-ups-070-charging",
        "gpm-ups-070-charging",
        "battery-070-charging",
        "xfpm-battery-070-charging",
        "xfpm-primary-070-charging",
    ],
    "battery-60-charging": [
        "battery-medium-charging",
        "gpm-primary-060-charging",
        "gpm-battery-060-charging",
        "xfpm-ups-060-charging",
        "gpm-ups-060-charging",
        "battery-060-charging",
        "xfpm-battery-060-charging",
        "xfpm-battery-ok-charging",
        "xfce4-battery-ok-charging",
        "xfpm-primary-060-charging",
    ],
    "battery-50-charging": [
        "gpm-primary-050-charging",
        "gpm-battery-050-charging",
        "xfpm-ups-050-charging",
        "gpm-ups-050-charging",
        "battery-050-charging",
        "xfpm-battery-050-charging",
        "xfpm-primary-050-charging",
    ],
    "battery-40-charging": [
        "battery-low-charging-symbolic",
        "gpm-battery-040-charging",
        "gpm-primary-040-charging",
        "gpm-ups-040-charging",
        "xfce4-battery-low-charging",
        "xfpm-battery-low-charging",
        "xfpm-primary-040-charging",
        "xfpm-ups-040-charging",
        "battery-040-charging",
        "xfpm-battery-040-charging",
        "battery-low-charging",
    ],
    "battery-30-charging": [
        "gpm-battery-030-charging",
        "gpm-primary-030-charging",
        "gpm-ups-030-charging",
        "xfpm-primary-030-charging",
        "xfpm-ups-030-charging",
        "battery-030-charging",
        "xfpm-battery-030-charging",
    ],
    "battery-20-charging": [
        "battery-caution-charging-symbolic",
        "gpm-battery-020-charging",
        "gpm-primary-020-charging",
        "gpm-ups-020-charging",
        "xfce4-battery-caution-charging",
        "xfce4-battery-critical-charging",
        "xfpm-battery-caution-charging",
        "xfpm-battery-critical-charging",
        "xfpm-primary-020-charging",
        "xfpm-ups-020-charging",
        "battery-020-charging",
        "xfpm-battery-020-charging",
        "battery-caution-charging",
    ],
    "battery-10-charging": [
        "gpm-battery-010-charging",
        "gpm-primary-010-charging",
        "gpm-ups-010-charging",
        "xfpm-primary-010-charging",
        "xfpm-ups-010-charging",
        "battery-010-charging",
        "xfpm-battery-010-charging",
    ],
    "battery-0-charging": [
        "battery-empty-charging-symbolic",
        "gpm-battery-000-charging",
        "gpm-primary-000-charging",
        "gpm-ups-000-charging",
        "xfpm-primary-000-charging",
        "xfpm-ups-000-charging",
        "battery-000-charging",
        "xfpm-battery-000-charging",
        "battery-empty-charging",
    ],
    "battery-missing": [
        "battery-missing-symbolic",
        "gpm-battery-missing",
        "gpm-primary-missing",
        "gpm-ups-missing",
        "xfce4-battery-missing",
        "xfpm-primary-missing",
        "xfpm-ups-missing",
        "xfpm-battery-missing",
    ],
    "bluetooth-active": [
        "blueberry-tray-active",
        "blueberry-tray",
        "blueman-active",
        "blueman",
        "blueman-tray-active",
        "blueman-tray",
        "bluetooth-active-symbolic",
    ],
    "bluetooth-disabled": [
        "blueberry-tray-disabled",
        "blueman-disabled",
        "blueman-tray-disabled",
    ],
    "bluetooth-disabled-10-symbolic": [],
    "bluetooth-disabled-20-symbolic": [],
    "bluetooth-disabled-30-symbolic": [],
    "bluetooth-disabled-40-symbolic": [],
    "bluetooth-disabled-50-symbolic": [],
    "bluetooth-disabled-60-symbolic": [],
    "bluetooth-disabled-70-symbolic": [],
    "bluetooth-disabled-80-symbolic": [],
    "bluetooth-disabled-90-symbolic": [],
    "bluetooth-disabled-symbolic": [],
    "bluetooth-paired": [],
    "bluetooth-paired-symbolic": [],
    "caffeine-cup-empty": [],
    "caffeine-cup-full": [],
    "camera-off": [],
    "camera-on": [
        "camera-ready",
    ],
    "dialog-information-symbolic": [],
    "display-brightness-symbolic": [
        "notification-display-brightness",
    ],
    "flameshot": [
        "flameshot-tray",
    ],
    "network-wired-offline": [
        "gnome-netstatus-disconn",
        "knemo-monitor-offline",
        "network-disconnected",
        "network-offline",
        "no-signal",
        "knemo-modem-offline",
        "knemo-network-offline",
        "knemo-wireless-offline",
    ],
    "network-error": [
        "gnome-netstatus-error",
        "knemo-monitor-error",
        "knemo-modem-error",
        "knemo-network-error",
        "knemo-wireless-error",
    ],
    "network-wired": [
        "gnome-netstatus-idle",
        "gnome-netstatus-txrx",
        "knemo-monitor-idle",
        "network-idle",
        "network-transmit-receive",
        "network-wired-symbolic",
        "nm-device-wired",
        "wired",
        "knemo-modem-idle",
        "knemo-monitor-transmit-receive",
        "knemo-network-idle",
        "knemo-wireless-idle",
        "connect_creating",
        "connect_established",
        "nm-device-wired-autoip",
        "knemo-modem-transmit-receive",
        "knemo-network-transmit-receive",
        "knemo-wireless-transmit-receive",
    ],
    "network-receive": [
        "gnome-netstatus-rx",
        "knemo-monitor-receive",
        "knemo-modem-receive",
        "knemo-network-receive",
        "knemo-wireless-receive",
    ],
    "network-transmit": [
        "gnome-netstatus-tx",
        "knemo-monitor-transmit",
        "knemo-modem-transmit",
        "knemo-network-transmit",
        "knemo-wireless-transmit",
    ],
    "gpm-brightness-lcd-disabled": [],
    "gpm-brightness-lcd-invalid": [],
    "gpm-keyboard-000": [],
    "gpm-keyboard-020": [],
    "gpm-keyboard-040": [],
    "gpm-keyboard-060": [],
    "gpm-keyboard-080": [],
    "gpm-keyboard-100": [],
    "network-cellular-secure-signal-excellent": [
        "gsm-3g-full-secure",
    ],
    "network-cellular-signal-excellent": [
        "gsm-3g-full",
        "nm-wwan-tower",
        "nm-device-wwan",
    ],
    "network-cellular-secure-signal-good": [
        "gsm-3g-high-secure",
    ],
    "network-cellular-signal-good": [
        "gsm-3g-high",
    ],
    "network-cellular-secure-signal-low": [
        "gsm-3g-low-secure",
        "network-cellular-secure-signal-weak",
    ],
    "network-cellular-signal-low": [
        "gsm-3g-low",
        "network-cellular-signal-weak",
    ],
    "network-cellular-secure-signal-ok": [
        "gsm-3g-medium-secure",
    ],
    "network-cellular-signal-ok": [
        "gsm-3g-medium",
    ],
    "network-cellular-secure-signal-none": [
        "gsm-3g-none-secure",
    ],
    "network-cellular-signal-none": [
        "gsm-3g-none",
    ],
    "network-wired-secure": [
        "gtk-dialog-authentication-panel",
        "krb-valid-ticket",
        "network-vpn",
        "network-wired-secure-symbolic",
        "nm-device-wired-secure",
        "nm-device-wired-secureoffline",
    ],
    "indicator-keyboard": [
        "input-keyboard",
    ],
    "indicator-messages-new": [
        "xfce-newmail",
    ],
    "indicator-messages-red": [],
    "indicator-messages": [
        "xfce-nomail",
    ],
    "krb-expiring-ticket": [],
    "krb-no-valid-ticket": [],
    "manjaro": [
        "manjaro-settings-manager-panel",
        "whiskermenu-manjaro",
        "manjaro-settings-manager",
        "manjaro-welcome",
        "start-here-manjaro",
    ],
    "microphone-sensitivity-muted-10-symbolic": [],
    "microphone-sensitivity-muted-20-symbolic": [],
    "microphone-sensitivity-muted-30-symbolic": [],
    "microphone-sensitivity-muted-40-symbolic": [],
    "microphone-sensitivity-muted-50-symbolic": [],
    "microphone-sensitivity-muted-60-symbolic": [],
    "microphone-sensitivity-muted-70-symbolic": [],
    "microphone-sensitivity-muted-80-symbolic": [],
    "microphone-sensitivity-muted-90-symbolic": [],
    "microphone-sensitivity-muted-symbolic": [],
    "mintupdate-checking": [
        "yum-indicator-updates",
    ],
    "mintupdate-error": [
        "yum-indicator-error",
    ],
    "mintupdate-installing": [
        "yum-indicator-working",
    ],
    "mintupdate-updates-available": [
        "pamac-tray-update",
        "yum-indicator-info",
    ],
    "mintupdate-up-to-date": [
        "pamac-tray-no-update",
        "yum-indicator-no-updates",
    ],
    "network-cellular-acquiring": [
        "network-cellular-signal-acquiring",
    ],
    "network-cellular-acquiring-symbolic": [],
    "network-cellular-connected-symbolic": [],
    "network-cellular-no-route": [],
    "network-cellular-no-route-symbolic": [],
    "network-cellular-offline": [],
    "network-cellular-offline-symbolic": [],
    "network-cellular-signal-excellent-secure-symbolic": [],
    "network-cellular-signal-excellent-symbolic": [],
    "network-cellular-signal-good-secure-symbolic": [],
    "network-cellular-signal-good-symbolic": [],
    "network-cellular-signal-none-secure-symbolic": [],
    "network-cellular-signal-none-symbolic": [],
    "network-cellular-signal-ok-secure-symbolic": [],
    "network-cellular-signal-ok-symbolic": [],
    "network-cellular-signal-weak-secure-symbolic": [],
    "network-cellular-signal-weak-symbolic": [],
    "network-offline-symbolic": [
        "network-wired-disconnected-symbolic",
        "network-wired-offline-symbolic",
    ],
    "network-vpn-acquiring": [],
    "network-vpn-lock-symbolic": [],
    "network-vpn-symbolic": [],
    "network-wired-acquiring": [],
    "network-wired-acquiring-symbolic": [],
    "network-wired-no-route": [],
    "network-wireless-acquiring": [],
    "network-wireless-hotspot": [],
    "network-wireless-no-route": [
        "network-wireless-no-route-symbolic",
    ],
    "network-wireless-offline": [],
    "nm-signal-100": [
        "network-wireless-connected",
        "network-wireless-signal-excellent",
        "network-wireless-signal-excellent-symbolic",
        "both-high-signal",
        "high-signal",
        "idle-high-signal",
        "receiving-high-signal",
        "transmitting-high-signal",
        "wireless-symbolic",
        "wireless-80-symbolic",
        "network-wireless-100",
        "network-wireless-100-symbolic",
        "network-wireless-signal-full-symbolic",
    ],
    "nm-signal-75": [
        "network-wireless-signal-good",
        "network-wireless-signal-good-symbolic",
        "both-good-signal",
        "good-signal",
        "idle-good-signal",
        "receiving-good-signal",
        "transmitting-good-signal",
        "network-wireless-60",
        "network-wireless-80",
    ],
    "nm-signal-50": [
        "network-wireless-signal-ok",
        "both-low-signal",
        "idle-low-signal",
        "low-signal",
        "receiving-low-signal",
        "transmitting-low-signal",
        "network-wireless-40",
        "network-wireless-40-symbolic",
        "network-wireless-50",
        "network-wireless-50-symbolic",
    ],
    "nm-signal-25": [
        "network-wireless-signal-low",
        "network-wireless-signal-ok-symbolic",
        "bad-signal",
        "both-bad-signal",
        "idle-bad-signal",
        "network-wireless-signal-weak",
        "receiving-bad-signal",
        "transmitting-bad-signal",
        "network-wireless-20",
        "network-wireless-20-symbolic",
    ],
    "nm-signal-0": [
        "network-wireless-offline-symbolic",
        "network-wireless-signal-none",
        "network-wireless-signal-none-symbolic",
        "network-wireless-signal-weak-symbolic",
        "nm-no-connection",
        "nm-signal-00",
        "network-wirelss-no-route-symbolic",
        "wireless-disabled-symbolic",
        "wireless-disconnect-symbolic",
        "wireless-0-symbolic",
        "network-wireless-0",
        "network-wireless-0-symbolic",
    ],
    "nm-signal-100-secure": [
        "network-wireless-secure-signal-excellent",
        "network-wireless-signal-excellent-secure-symbolic",
        "both-high-signal-lock",
        "high-signal-lock",
        "idle-high-signal-lock",
        "receiving-high-signal-lock",
        "transmitting-high-signal-lock",
        "network-wireless-signal-full-secure-symbolic",
        "network-wireless-100-locked",
    ],
    "nm-signal-75-secure": [
        "network-wireless-secure-signal-good",
        "network-wireless-signal-good-secure-symbolic",
        "both-good-signal-lock",
        "good-signal-lock",
        "idle-good-signal-lock",
        "receiving-good-signal-lock",
        "transmitting-good-signal-lock",
        "network-wireless-60-locked",
        "network-wireless-80-locked",
        "network-wireless-signal-high-secure-symbolic",
    ],
    "nm-signal-50-secure": [
        "network-wireless-secure-signal-ok",
        "both-low-signal-lock",
        "idle-low-signal-lock",
        "low-signal-lock",
        "receiving-low-signal-lock",
        "transmitting-low-signal-lock",
        "network-wireless-40-locked",
        "network-wireless-50-locked",
        "network-wireless-signal-medium-secure-symbolic",
    ],
    "nm-signal-25-secure": [
        "network-wireless-secure-signal-low",
        "network-wireless-signal-ok-secure-symbolic",
        "bad-signal-lock",
        "both-bad-signal-lock",
        "idle-bad-signal-lock",
        "receiving-bad-signal-lock",
        "transmitting-bad-signal-lock",
        "network-wireless-20-locked",
        "network-wireless-signal-low-secure-symbolic",
    ],
    "nm-signal-0-secure": [
        "network-wireless-secure-signal-none",
        "network-wireless-signal-weak-secure-symbolic",
        "nm-signal-00-secure",
        "network-wireless-0-locked",
        "network-wirelss-no-route-secure-symbolic",
    ],
    "night-light-disabled-10-symbolic": [],
    "night-light-disabled-20-symbolic": [],
    "night-light-disabled-30-symbolic": [],
    "night-light-disabled-40-symbolic": [],
    "night-light-disabled-50-symbolic": [],
    "night-light-disabled-60-symbolic": [],
    "night-light-disabled-70-symbolic": [],
    "night-light-disabled-80-symbolic": [],
    "night-light-disabled-90-symbolic": [],
    "night-light-disabled-symbolic": [],
    "night-light-symbolic": [],
    "nm-vpn-lock": [
        "nm-vpn-active-lock",
    ],
    "notification-disabled-10-symbolic": [],
    "notification-disabled-20-symbolic": [],
    "notification-disabled-30-symbolic": [],
    "notification-disabled-40-symbolic": [],
    "notification-disabled-50-symbolic": [],
    "notification-disabled-60-symbolic": [],
    "notification-disabled-70-symbolic": [],
    "notification-disabled-80-symbolic": [],
    "notification-disabled-90-symbolic": [],
    "notification-disabled-symbolic": [],
    "notification-new-10-symbolic": [],
    "notification-new-20-symbolic": [],
    "notification-new-30-symbolic": [],
    "notification-new-40-symbolic": [],
    "notification-new-50-symbolic": [],
    "notification-new-60-symbolic": [],
    "notification-new-70-symbolic": [],
    "notification-new-80-symbolic": [],
    "notification-new-90-symbolic": [],
    "notification-new-symbolic": [],
    "notification-symbolic": [],
    "onboard-panel": [],
    "optimus-indicator-intel": [],
    "optimus-indicator-nvidia": [],
    "printer-printing-symbolic": [],
    "process-working-symbolic": [],
    "riot-tray": [],
    "slack-indicator-highlight": [],
    "slack-indicator": [],
    "slack-indicator-unread": [],
    "start-here-symbolic": [],
    "state-download": [],
    "state-error": [],
    "state-information": [],
    "state-offline": [],
    "state-ok": [],
    "state-pause": [],
    "state-sync": [],
    "state-warning": [],
    "system-devices-panel": [
        "system-shutdown-symbolic",
    ],
    "system-search-symbolic": [],
    "telegram": [
        "telegram-attention-panel",
        "telegram-mute-panel",
        "telegram-panel",
        "org.telegram.desktop-symbolic",
        "org.telegram.desktop-mute-symbolic",
        "org.telegram.desktop-attention-symbolic",
        "org.telegram.desktop.png",
    ],
    "uget-tray-default": [],
    "uget-tray-downloading": [],
    "uget-tray-error": [],
    "clipit-trayicon": [],
    "input-touchpad-off": [],
    "input-touchpad-on": [],
    "laptop-connected": [],
    "laptop-disconnected": [],
    "laptop-trusted": [],
    "redshift-status-off": [],
    "redshift-status-on": [],
    "smartphone-connected": [],
    "smartphone-disconnected": [],
    "smartphone-trusted": [],
    "tablet-connected": [],
    "tablet-disconnected": [],
    "tablet-trusted": [],
    "update-high": [],
    "update-low": [],
    "update-medium": [],
    "update-none": [],
}
